version: '3.1'

services:
  dev-mysql:
    image: mysql:5.7.42
    ports:
        - 63306:3306
    volumes:
        - ./mysql/data:/var/lib/mysql
        - ./mysql/conf.d:/etc/mysql/conf.d
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root

  dev-redis:
    image: redis:5.0-alpine
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - "56379:6379"
    volumes:
      - ./redis/data:/data
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
  dev-nginx:
    image: 'nginx:1.16.0-alpine'
    container_name: dev-nginx
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/log:/var/log/nginx
      - ./nginx/www:/var/www
    ports:
      - 18081:80
      - 18443:443
  dev-minio:
    image: quay.io/minio/minio:RELEASE.2023-12-20T01-00-02Z
    container_name: dev-minio
    ports:
      - 19000:9000
      - 19001:9001
    environment:
      MINIO_ROOT_USER: root
      MINIO_ROOT_PASSWORD: JtwlIO998
    volumes:
      - ./minio/data:/data
    command: server --console-address ":9001" /data
    restart: always
